name: Automated Updates

on:
  push:
    branches:
      - master

jobs:
  update-data:
    runs-on: ubuntu-latest

    if: ${{ github.repository_id == '247692460' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requests library
        run: python -m pip install requests

      - name: Run Python museum script
        run: python .github/scripts/updateMuseum.py

      - name: Run Python gemstone slot unlock costs script
        run: python .github/scripts/updateGemstoneCosts.py

      - name: Run Python george pet prices script
        run: python .github/scripts/updateGeorgePrices.py

      - name: Run Python essence costs script
        run: python .github/scripts/updateEssenceCosts.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add constants/museum.json
          git add constants/gemstonecosts.json
          git add constants/george.json
          git add constants/essencecosts.json
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update data from Hypixel API"
          git push --force origin HEAD:bot/automated-updates

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bot/automated-updates
          base: master
          title: "Automated Updates"
          body: "This pull request contains the latest data from the Hypixel API."
          labels: "automated update"