# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validatejson:
    name: Validate json
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install jsonlint
        run: npm i jsonlint
      - name: lint constants
        run: |
          #!/bin/bash
          echo "Linting contants..."
          for filename in constants/*.json; do
            npx jsonlint "$filename" > /dev/null
          done
          echo "Linted."
      - name: lint items
        run: |
          #!/bin/bash
          echo "Linting items..."
          for filename in items/*.json; do
            npx jsonlint "$filename" > /dev/null
          done
          echo "Linted"
